using System;
using System.Drawing;
using System.Text.RegularExpressions;
using System.Windows.Forms;
using CarRentalSystem.DTOs; // CRITICAL: This allows us to use RegistrationDTO

using CarRentalSystem.Services;

namespace CarRentalSystem.Forms
{
    public partial class Register_Page : Form
    {
        private CustomerService _customerService;

        public Register_Page()
        {
            InitializeComponent();
            _customerService = new CustomerService();

            btnRegister.Click += btnRegister_Click;
            BackBtn.Click += BackBtn_Click;

            HideErrorLabels();
        }

        private void HideErrorLabels()
        {
            UsernameErrorLabel.Visible = false;
            EmailErrorLabel.Visible = false;
            PasswordErrorLabel.Visible = false;
        }


        private void btnRegister_Click(object sender, EventArgs e)
        {
            HideErrorLabels(); // Reset errors on each click
            bool isValid = true;

            string first = txtFirstName.Text.Trim();
            string last = txtLastName.Text.Trim();
            string username = txtUsername.Text.Trim();
            string email = txtEmail.Text.Trim();
            string password = txtPassword.Text; // Never trim passwords!

            // 1. Empty Check
            if (string.IsNullOrWhiteSpace(first) || string.IsNullOrWhiteSpace(last) ||
                string.IsNullOrWhiteSpace(username) || string.IsNullOrWhiteSpace(email) ||
                string.IsNullOrWhiteSpace(password))
            {
                MessageBox.Show("Please fill out all fields before continuing.", "Required Fields", MessageBoxButtons.OK, MessageBoxIcon.Warning);
                return;
            }

            // 2. Email Format Validation
            if (!Regex.IsMatch(email, @"^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.(com|net|org|edu|gov|eg|co)$", RegexOptions.IgnoreCase))
            {
                EmailErrorLabel.Text = "Please enter a valid email (e.g., .com, .net, .eg).";
                EmailErrorLabel.Visible = true;
                isValid = false;
            }

            // 3. Password Strength
            if (password.Length < 6)
            {
                PasswordErrorLabel.Text = "Password is too weak (min 6 characters).";
                PasswordErrorLabel.Visible = true;
                isValid = false;
            }

            // 4. Database Checks (Making sure neither Username NOR Email are taken)
            if (_customerService.IsUsernameTaken(username))
            {
                UsernameErrorLabel.Text = "Username taken. Try another one.";
                UsernameErrorLabel.Visible = true;
                isValid = false;
            }

            if (_customerService.IsEmailTaken(email))
            {
                EmailErrorLabel.Text = "An account with this email already exists.";
                EmailErrorLabel.Visible = true;
                isValid = false;
            }

            // 5. Transition Logic
            if (isValid)
            {
                // Pack the data
                var newUserInfo = new RegistrationDTO
                {
                    FirstName = first,
                    LastName = last,
                    Username = username,
                    Email = email,
                    Password = password
                };

                this.Hide();

                using (var otpForm = new Email_Verification(newUserInfo))
                {
                    // If the user finishes Step 3, the wizard sends an "OK" signal.
                    if (otpForm.ShowDialog() == DialogResult.OK)
                    {
                        this.Close(); // Completely close this form so they drop into the Login screen
                    }
                    else
                    {
                        // ONLY show this form again if they clicked "Back" or X'd out of the OTP screen!
                        this.Show();
                    }
                }
            }
        }

        private void BackBtn_Click(object sender, EventArgs e)
        {
            // Returns to the Login page
            this.Close();
        }

        // Empty event handlers generated by the visual designer
        private void label3_Click(object sender, EventArgs e) { }
        private void label5_Click(object sender, EventArgs e) { }
        private void label3_Click_1(object sender, EventArgs e) { }
        private void errorLabel_Click(object sender, EventArgs e) { }
    }
}